{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n    \n>       raise Exception('oops')\nE       Exception: oops\n\ntest_alluredemo.py:21: Exception"}, "start": 1616899047699, "stop": 1616899047699, "uuid": "2f0bd0c5-16d3-470e-b440-800765f15a91", "historyId": "fb799eecaee64eb20ac70a0047ddd7ff", "testCaseId": "54327feac6bee8ccd45a88d670bf2886", "fullName": "test_alluredemo#test_broken", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "SKY-20200805OYN"}, {"name": "thread", "value": "2164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}